#!/usr/bin/python3
# -*- coding: utf-8 -*-

#
# Генерация исключений
#

# Иногда возникает необходимость вручную сгенерировать
# то или иное исключение. Для этого применяется оператор raise.

try:
    number1 = int(input("Введите первое число: "))
    number2 = int(input("Введите второе число: "))
    if number2 == 0:
        raise Exception("Второе число не должно быть равно 0")
    print("Результат деления двух чисел:", number1/number2)
except ValueError:
    print("Введены некорректные данные")
except Exception as e:
    print(e)
print("Завершение программы")

# При вызове исключения мы можем ему передать сообщение, которое
# затем можно вывести пользователю
